[package]
name = "aero2solver"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1"
darknet = "0.4"
anyhow = "1.0"
reqwest = { version = "0.11", default-features = false, features = ["blocking"] }
tl = "0.7"
image = "0.24"